#!/usr/bin/env node
/**
 * generate: every generated file of this repository, from the contract, in a fixed order.
 *
 *   1. lint contracts/openapi/ever-platform.v1.yaml (Redocly; only `x-ever-*` extensions; every
 *      operation has `x-ever-row` and typed bodies)
 *   2. TypeScript types of paths, components and operations (openapi-typescript)
 *   3. TypeScript types of the JSON Schemas and the schema documents (json-schema-to-typescript)
 *   4. Rust types of the components and the JSON Schemas (typify, `cargo run -p xtask -- typify`)
 *   5. typed integrations, constants, rows and problem codes (TypeScript and Rust)
 *   6. the outbound-call table and the statistics example inside the docs pages
 *   7. contracts/generated/outbound-calls.json and contracts/generated/row-coverage.json
 *   8. generated.lock: the sha256 of every generated file
 *
 *   node tools/generate.mjs           write
 *   node tools/generate.mjs --check   regenerate into memory, compare with the committed files,
 *                                     then `git diff --exit-code` over the generated paths
 *
 * Output is deterministic: sorted keys, LF, no timestamps or tool versions, pinned tools.
 */
import { execFileSync } from 'node:child_process';
import { existsSync, mkdtempSync, readdirSync, readFileSync, rmSync } from 'node:fs';
import { createRequire } from 'node:module';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { compile } from 'json-schema-to-typescript';
import openapiTS, { astToString } from 'openapi-typescript';
import YAML from 'yaml';
import { diffOutputs, REPO, readJson, sha256, stableJson, writeText } from './lib/common.mjs';
import { forRust, inlineCommon, typeName } from './lib/schema-prep.mjs';
import { checkRows } from './sync-contract.mjs';

const require = createRequire(import.meta.url);
const SPEC = 'contracts/openapi/ever-platform.v1.yaml';
const TS = 'packages/ts/connect-contracts/src/generated';
const RS = 'crates/ever-connect-contracts/src/generated';
const TS_HEADER = '// Generated by tools/generate.mjs from the contract files. Do not edit by hand.\n';
const RS_HEADER = '// Generated by tools/generate.mjs from the contract files. Do not edit by hand.\n';
const METHODS = ['get', 'put', 'post', 'delete', 'patch'];

export const SCHEMA_DOCS = [
  { file: 'ever.stats.v1.json', key: 'stats', type: 'StatsReportV1', module: 'stats_v1' },
  { file: 'ever.entitlement.v1.json', key: 'entitlement', type: 'EntitlementV1', module: 'entitlement_v1' },
  { file: 'ever.consent.v1.json', key: 'consent', type: 'ConsentV1', module: 'consent_v1' },
  { file: 'ever.key-manifest.v1.json', key: 'keyManifest', type: 'KeyManifestV1', module: 'key_manifest_v1' },
  { file: 'ever.usage.v1.json', key: 'usage', type: 'UsageReportV1', module: 'usage_v1' },
];

const readText = (p) => readFileSync(join(REPO, p), 'utf8');
const lf = (t) => t.replace(/\r\n/g, '\n');

function load() {
  const spec = YAML.parse(readText(SPEC));
  // EVER_SDK_ROWS_JSON points the generator at another table (the generator's own tests use it).
  const rowsDoc = readJson(process.env.EVER_SDK_ROWS_JSON ?? join(REPO, 'contracts/openapi/rows.json'));
  const pending = readJson(join(REPO, 'contracts/openapi/pending-upstream.json'));
  const constants = readJson(join(REPO, 'contracts/constants.json'));
  // EVER_SDK_CATALOG_JSON points the generator at another catalog (the generator's own tests use it).
  const catalog = readJson(process.env.EVER_SDK_CATALOG_JSON ?? join(REPO, 'contracts/integrations/catalog.v1.json'));
  const vendorDoc = readJson(join(REPO, 'contracts/VENDOR.json'));
  const integrations = {};
  for (const key of constants.integration_keys) integrations[key] = readJson(join(REPO, `contracts/integrations/${key}.json`));
  const events = {};
  for (const type of constants.feed_event_types) {
    const file = readdirSync(join(REPO, 'contracts/schemas/events')).find((f) => f.startsWith(`${type}.v`));
    if (!file) throw new Error(`no schema file for event type ${type}`);
    events[type] = { file, schema: readJson(join(REPO, 'contracts/schemas/events', file)) };
  }
  const common = readJson(join(REPO, 'contracts/schemas/events/common.schema.json'));
  const envelope = readJson(join(REPO, 'contracts/schemas/events/envelope.schema.json'));
  const schemas = Object.fromEntries(SCHEMA_DOCS.map((d) => [d.key, readJson(join(REPO, 'contracts/schemas', d.file))]));
  return { spec, rowsDoc, pending, constants, catalog, vendorDoc, integrations, events, common, envelope, schemas };
}

function operations(spec) {
  const out = [];
  for (const [path, item] of Object.entries(spec.paths))
    for (const method of METHODS) if (item[method]) out.push({ method, path, op: item[method] });
  return out;
}

// ---------------------------------------------------------------------------------------- step 1
function lint(ctx) {
  const problems = [];
  const walk = (node, at) => {
    if (Array.isArray(node)) return node.forEach((n, i) => walk(n, `${at}/${i}`));
    if (!node || typeof node !== 'object') return;
    for (const [k, v] of Object.entries(node)) {
      // Extension keys only where OpenAPI allows them: not inside `properties`, `paths` names, examples.
      const container = at.split('/').pop();
      const isName = ['properties', 'paths', 'schemas', 'responses', 'securitySchemes', 'headers', 'content', '$defs'].includes(container);
      if (!isName && k.startsWith('x-') && !k.startsWith('x-ever-')) problems.push(`${at}/${k}: only x-ever-* extensions are allowed`);
      if (k !== 'example' && k !== 'examples') walk(v, `${at}/${k}`);
    }
  };
  walk(ctx.spec, '#');
  for (const { method, path, op } of operations(ctx.spec)) {
    const where = `${method.toUpperCase()} ${path} (${op.operationId})`;
    if (!Number.isInteger(op['x-ever-row'])) problems.push(`${where}: no x-ever-row`);
    const typed = (schema) =>
      schema &&
      (schema.$ref || schema.type || schema.oneOf || schema.anyOf || schema.allOf || schema.properties || 'const' in schema || schema.enum);
    for (const [mt, media] of Object.entries(op.requestBody?.content ?? {}))
      if (!typed(media.schema)) problems.push(`${where}: request body ${mt} has no typed schema`);
    for (const [status, response] of Object.entries(op.responses ?? {})) {
      if (!/^2/.test(status)) continue;
      for (const [mt, media] of Object.entries(response.content ?? {}))
        if (!typed(media.schema)) problems.push(`${where}: ${status} ${mt} has no typed schema`);
    }
  }
  const ids = new Set(operations(ctx.spec).map((o) => o.op.operationId));
  problems.push(...checkRows(ctx.rowsDoc, ids, ctx.pending).problems);
  for (const r of ctx.rowsDoc.rows) {
    for (const op of operations(ctx.spec).filter((o) => r.operation_ids.includes(o.op.operationId)))
      if (op.op['x-ever-row'] !== r.row)
        problems.push(`${op.op.operationId}: x-ever-row ${op.op['x-ever-row']} but rows.json says ${r.row}`);
  }
  // Hidden catalog keys never reach the generated output, and the vendored catalog lists none.
  const hidden = ctx.catalog.integrations.filter((i) => i.status === 'hidden').map((i) => i.key);
  for (const key of hidden) {
    problems.push(`the vendored catalog lists hidden integration ${key}; public copies list no hidden row`);
    if (ctx.constants.integration_keys.includes(key)) problems.push(`hidden integration ${key} is listed in constants.integration_keys`);
    if (ctx.rowsDoc.rows.some((r) => r.integration === key)) problems.push(`hidden integration ${key} is named by a row`);
  }
  if (problems.length > 0) throw new Error(`lint:\n  ${problems.join('\n  ')}`);

  const pkg = require.resolve('@redocly/cli/package.json', { paths: [REPO] });
  const bin = readJson(pkg).bin;
  const cli = join(pkg, '..', typeof bin === 'string' ? bin : (bin.redocly ?? Object.values(bin)[0]));
  try {
    execFileSync(process.execPath, [cli, 'lint', SPEC, '--config', 'redocly.yaml', '--format', 'stylish'], {
      cwd: REPO,
      stdio: ['ignore', 'pipe', 'pipe'],
      env: { ...process.env, REDOCLY_TELEMETRY: 'off', REDOCLY_SUPPRESS_UPDATE_NOTICE: 'true', NO_COLOR: '1' },
    });
  } catch (error) {
    throw new Error(`redocly lint failed:\n${error.stdout?.toString() ?? ''}${error.stderr?.toString() ?? ''}`);
  }
}

// ---------------------------------------------------------------------------------------- step 2
async function openapiTypes(ctx) {
  const ast = await openapiTS(structuredClone(ctx.spec), { immutable: true, alphabetize: true });
  return `${TS_HEADER}// The type half of the instance-facing contract: paths, components and operations.\n\n${astToString(ast)}`;
}

// ---------------------------------------------------------------------------------------- step 3
const JSTT = {
  bannerComment: '',
  additionalProperties: false,
  declareExternallyReferenced: true,
  enableConstEnums: false,
  strictIndexSignatures: true,
  unreachableDefinitions: false,
  format: true,
  style: { singleQuote: true, printWidth: 100, trailingComma: 'all' },
  $refOptions: { resolve: { http: false, file: false } },
};

function forTypescript(schema) {
  const copy = structuredClone(schema);
  delete copy.$id;
  delete copy.title;
  return copy;
}

/** Literal TypeScript for a JSON value (JSON is valid TypeScript). */
const literal = (value) => JSON.stringify(value, null, 2);

/** Prefixes every type a schema compile declares (except the root) with the root's name. */
function prefixTypes(ts, root) {
  const names = [...ts.matchAll(/export (?:type|interface) (\w+)/g)].map((m) => m[1]).filter((n) => n !== root);
  let out = ts;
  for (const n of names.sort((a, b) => b.length - a.length)) out = out.replace(new RegExp(`\\b${n}\\b`, 'g'), `${root}${n}`);
  return out;
}

async function schemaTypes(ctx) {
  const parts = [TS_HEADER, '// Types of the JSON Schemas and the schema documents themselves.\n\n'];
  parts.push(
    '/** A JSON Schema document, as shipped in this package. */\nexport type JsonSchemaDocument = { readonly [key: string]: unknown };\n\n',
  );
  for (const doc of SCHEMA_DOCS) {
    const ts = await compile(forTypescript(ctx.schemas[doc.key]), doc.type, JSTT);
    parts.push(`${prefixTypes(ts.trim(), doc.type)}\n\n`);
  }
  // Event data types, one per instance-audience type.
  const eventTypes = Object.keys(ctx.events);
  const eventNames = {};
  for (const type of eventTypes) {
    const name = `${typeName(type)}V${/\.v(\d+)\./.exec(ctx.events[type].file)[1]}`;
    eventNames[type] = name;
    const ts = await compile(forTypescript(inlineCommon(ctx.events[type].schema, ctx.common)), name, JSTT);
    parts.push(`${prefixTypes(ts.trim(), name)}\n\n`);
  }
  parts.push('/** The `data` type of every instance-audience event type. */\nexport interface EventDataByType {\n');
  for (const type of eventTypes) parts.push(`  '${type}': ${eventNames[type]};\n`);
  parts.push('}\n\n/** An event type an installation receives on its feed. */\nexport type FeedEventType = keyof EventDataByType;\n\n');
  parts.push('/** The JSON Schema documents (closed contracts). */\nexport const SCHEMAS = {\n');
  for (const doc of SCHEMA_DOCS)
    parts.push(`  ${doc.key}: ${literal(ctx.schemas[doc.key]).replace(/\n/g, '\n  ')} as JsonSchemaDocument,\n`);
  parts.push(
    '} as const;\n\n/** The event schemas: the shared envelope and common definitions, and one `data` schema per type. */\nexport const EVENT_SCHEMAS = {\n',
  );
  parts.push(`  envelope: ${literal(ctx.envelope).replace(/\n/g, '\n  ')} as JsonSchemaDocument,\n`);
  parts.push(`  common: ${literal(ctx.common).replace(/\n/g, '\n  ')} as JsonSchemaDocument,\n`);
  parts.push('  data: {\n');
  for (const type of eventTypes)
    parts.push(`    '${type}': ${literal(ctx.events[type].schema).replace(/\n/g, '\n    ')} as JsonSchemaDocument,\n`);
  parts.push('  },\n} as const;\n');
  return parts.join('');
}

// ---------------------------------------------------------------------------------------- step 4
function rustBundle(ctx) {
  const components = {};
  for (const [name, schema] of Object.entries(ctx.spec.components.schemas))
    Object.assign(components, forRust(schema, `${name}_`, { rootName: name }));
  const modules = SCHEMA_DOCS.map((d) => ({
    name: d.module,
    doc: `Types of \`contracts/schemas/${d.file}\`.`,
    definitions: forRust(ctx.schemas[d.key], '', { rootName: d.type }),
  }));
  for (const [type, { file, schema }] of Object.entries(ctx.events)) {
    const version = /\.v(\d+)\./.exec(file)[1];
    modules.push({
      name: `${type.replace(/^ever\./, '').replace(/[^a-z0-9]+/g, '_')}_v${version}`,
      doc: `Data of the \`${type}\` event (\`contracts/schemas/events/${file}\`).`,
      definitions: forRust(inlineCommon(schema, ctx.common), '', { rootName: `${typeName(type)}V${version}` }),
    });
  }
  const header = (what) => `${RS_HEADER}//! ${what}\n#![allow(missing_docs, clippy::all, unused_imports, irrefutable_let_patterns)]\n`;
  return {
    files: [
      {
        file: 'openapi.rs',
        header: header('Request and response types of the instance-facing contract.'),
        modules: [
          { name: 'components', doc: 'Every component schema of `contracts/openapi/ever-platform.v1.yaml`.', definitions: components },
        ],
      },
      { file: 'schemas.rs', header: header('Types of the JSON Schemas and the instance-audience event data.'), modules },
    ],
  };
}

function rustTypes(ctx) {
  const dir = mkdtempSync(join(tmpdir(), 'ever-connect-sdk-typify-'));
  try {
    const input = join(dir, 'bundle.json');
    writeText(input, JSON.stringify(rustBundle(ctx)));
    const cargo = process.env.CARGO ?? 'cargo';
    execFileSync(cargo, ['run', '--quiet', '--locked', '-p', 'xtask', '--', 'typify', input, dir], {
      cwd: REPO,
      stdio: ['ignore', 'pipe', 'pipe'],
    });
    return {
      [`${RS}/openapi.rs`]: lf(readFileSync(join(dir, 'openapi.rs'), 'utf8')),
      [`${RS}/schemas.rs`]: lf(readFileSync(join(dir, 'schemas.rs'), 'utf8')),
    };
  } catch (error) {
    throw new Error(`typify failed:\n${error.stderr?.toString() ?? error.message}`);
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
}

/** The name typify gives a schema: its `_` segments joined in UpperCamelCase. */
const rustTypeName = (name) =>
  name
    .split('_')
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join('');

/** The typed round-trip dispatch the Rust fixture test uses: one arm per generated root type. */
function rustTypedDispatch(ctx) {
  const components = Object.keys(ctx.spec.components.schemas).sort();
  const events = Object.entries(ctx.events).map(([type, { file }]) => {
    const version = /\.v(\d+)\./.exec(file)[1];
    return [type, `${type.replace(/^ever\./, '').replace(/[^a-z0-9]+/g, '_')}_v${version}`, `${typeName(type)}V${version}`];
  });
  return `${RS_HEADER}//! Typed round trip for the fixture tests: deserialize a document into the generated type its
//! schema names and serialize it back.
#![allow(dead_code)]

use ever_connect_contracts::{openapi::components, schemas};
use serde::{Serialize, de::DeserializeOwned};
use serde_json::Value;

fn rt<T: DeserializeOwned + Serialize>(value: &Value) -> Result<Value, String> {
    let typed: T = serde_json::from_value(value.clone()).map_err(|e| e.to_string())?;
    serde_json::to_value(typed).map_err(|e| e.to_string())
}

/// A contract component schema, by name.
pub fn component(name: &str, value: &Value) -> Option<Result<Value, String>> {
    Some(match name {
${components.map((n) => `        ${JSON.stringify(n)} => rt::<components::${rustTypeName(n)}>(value),`).join('\n')}
        _ => return None,
    })
}

/// One of the JSON Schemas, by key.
pub fn schema(key: &str, value: &Value) -> Option<Result<Value, String>> {
    Some(match key {
${SCHEMA_DOCS.map((d) => `        ${JSON.stringify(d.key)} => rt::<schemas::${d.module}::${d.type}>(value),`).join('\n')}
        _ => return None,
    })
}

/// The data of an instance-audience event, by type.
pub fn event(event_type: &str, value: &Value) -> Option<Result<Value, String>> {
    Some(match event_type {
${events.map(([t, m, n]) => `        ${JSON.stringify(t)} => rt::<schemas::${m}::${n}>(value),`).join('\n')}
        _ => return None,
    })
}
`;
}

function rustfmt(source) {
  const bin = process.env.RUSTFMT ?? 'rustfmt';
  try {
    return lf(
      execFileSync(bin, ['--edition', '2024', '--emit', 'stdout'], {
        cwd: REPO,
        input: source,
        encoding: 'utf8',
        maxBuffer: 64 * 1024 * 1024,
        stdio: ['pipe', 'pipe', 'pipe'],
      }),
    );
  } catch (error) {
    throw new Error(`rustfmt failed:\n${error.stderr?.toString() ?? error.message}`);
  }
}

// ---------------------------------------------------------------------------------------- step 5
function integrationsTs(ctx) {
  const keys = ctx.constants.integration_keys;
  const out = [TS_HEADER, '// The integration definitions (contracts/integrations/<key>.json), typed.\n\n'];
  out.push(
    `/** Every integration key a product can show (hidden catalog keys are never listed). */\nexport type IntegrationKey =\n${keys.map((k) => `  | '${k}'`).join('\n')};\n\n`,
  );
  out.push(`export const INTEGRATION_KEYS = ${literal(keys)} as const satisfies readonly IntegrationKey[];\n\n`);
  out.push(`/** One row of what an integration moves. */
export interface IntegrationScopeRow {
  readonly field_path: string;
  readonly direction: 'to_ever' | 'from_ever';
  readonly form: 'clear' | 'salted_hash' | 'count' | 'id' | 'url';
  readonly frequency: 'once' | 'on_action' | 'on_change' | 'daily' | 'events';
  readonly required: boolean;
  readonly purpose: string;
  readonly retention: string;
  readonly group?: string;
}

/** An integration definition: the same data app.ever.co renders its consent screen from. */
export interface IntegrationDefinition {
  readonly key: IntegrationKey;
  readonly name: string;
  readonly description: string;
  readonly category: string;
  readonly owner_module: string;
  readonly direction: 'outbound' | 'inbound' | 'both';
  readonly defaults: { readonly cloud: boolean; readonly self_hosted: boolean };
  readonly availability: {
    readonly cloud: 'enabled' | 'available' | 'disabled' | 'not_applicable';
    readonly self_hosted: 'enabled' | 'available' | 'disabled' | 'not_applicable';
  };
  readonly requires_feature: string | null;
  readonly products: readonly string[];
  readonly phase: number;
  readonly status: 'active' | 'coming_soon';
  readonly scope_version: number;
  readonly revoke_effect: string;
  readonly notes?: string;
  readonly scope: readonly IntegrationScopeRow[];
  readonly docs_anchor: string;
}

`);
  out.push('export const INTEGRATIONS: { readonly [K in IntegrationKey]: IntegrationDefinition } = {\n');
  for (const key of keys) out.push(`  ${key}: ${literal(ctx.integrations[key]).replace(/\n/g, '\n  ')},\n`);
  out.push('};\n');
  return out.join('');
}

function constantsTs(ctx) {
  return `${TS_HEADER}// contracts/constants.json, typed.\n\nexport const CONSTANTS = ${literal(ctx.constants)} as const;\n\nexport type Constants = typeof CONSTANTS;\n\n/** Every product code; \`demand\` accepts no connection. */\nexport type Product = (typeof CONSTANTS.products)[number];\n\n/** The instance-audience event types (the instance feed). */\nexport const FEED_EVENT_TYPES = CONSTANTS.feed_event_types;\n`;
}

/** The rows as products render them (contracts/generated/outbound-calls.json). */
function outboundCalls(ctx) {
  const ops = operations(ctx.spec);
  const productsAll = ctx.rowsDoc.products_all;
  return {
    description:
      'Every outbound call the Ever Platform modules of a product can make, generated from contracts/openapi/rows.json and contracts/openapi/ever-platform.v1.yaml. Products render their outbound-call page from this file.',
    contracts_version: ctx.constants.contracts_version,
    rows: ctx.rowsDoc.rows.map((r) => {
      const endpoints = r.pending_upstream
        ? ctx.pending.operations
            .filter((p) => p.row === r.row)
            .map((p) => ({ method: p.method, path: p.path, operation_id: p.operation_id, status: 'pending_upstream' }))
        : r.operation_ids.map((id) => {
            const o = ops.find((x) => x.op.operationId === id);
            return {
              method: o.method.toUpperCase(),
              path: o.path,
              operation_id: id,
              status: ctx.vendorDoc.openapi.provisional_operations.includes(id) ? 'provisional' : 'pinned',
            };
          });
      const products = r.integration ? (ctx.integrations[r.integration]?.products ?? []) : r.products === 'all' ? productsAll : r.products;
      return {
        row: r.row,
        title: r.title,
        module: r.module,
        group: r.group,
        integration: r.integration ?? null,
        auth: r.auth,
        endpoints,
        trigger: r.trigger,
        payload: r.payload,
        cadence: r.cadence,
        disable: r.disable,
        products,
        phase: r.phase,
      };
    }),
  };
}

function rowCoverage(ctx) {
  const ops = operations(ctx.spec);
  const codes = new Set([...ctx.spec.components.schemas.ErrorCode.enum, ...ctx.pending.problem_codes.map((c) => c.code)]);
  const problems = [];
  const rows = ctx.rowsDoc.rows.map((r) => {
    const rowOps = r.pending_upstream
      ? ctx.pending.operations
          .filter((p) => p.row === r.row)
          .map((p) => ({
            operation_id: p.operation_id,
            method: p.method,
            path: p.path,
            success: Object.keys(p.responses)
              .filter((s) => /^2/.test(s))
              .map(Number),
          }))
      : r.operation_ids.map((id) => {
          const o = ops.find((x) => x.op.operationId === id);
          return {
            operation_id: id,
            method: o.method.toUpperCase(),
            path: o.path,
            success: Object.keys(o.op.responses)
              .filter((s) => /^(2|304)/.test(s))
              .map(Number),
          };
        });
    const documented = new Set(
      r.pending_upstream
        ? ctx.pending.operations.filter((p) => p.row === r.row).flatMap((p) => Object.keys(p.responses))
        : rowOps.flatMap((o) => Object.keys(ops.find((x) => x.op.operationId === o.operation_id).op.responses)),
    );
    const errors = r.errors.map(([status, code, flag]) => {
      if (!codes.has(code)) problems.push(`row ${r.row}: ${code} is not a problem code of the contract`);
      const isDocumented = flag !== 'spec-gap';
      if (isDocumented && !documented.has(String(status)))
        problems.push(`row ${r.row}: status ${status} is not documented for its operations (mark it spec-gap)`);
      return { status, code, documented: isDocumented };
    });
    return { row: r.row, operations: rowOps, errors };
  });
  if (problems.length > 0) throw new Error(`row coverage:\n  ${problems.join('\n  ')}`);
  return {
    description:
      'Every (row, status, problem code) the outbound-call table documents. The mock platform test suite answers each pair; `documented: false` marks a pair the platform contract does not document yet for that operation.',
    rows,
  };
}

function problemsTs(ctx) {
  const codes = ctx.spec.components.schemas.ErrorCode.enum;
  const pendingCodes = ctx.pending.problem_codes.map((c) => c.code).filter((c) => !codes.includes(c));
  return `${TS_HEADER}// Problem codes: the contract's ErrorCode enum, plus the codes still pending upstream.\n\nexport const PROBLEM_CODES = ${literal([...codes, ...pendingCodes])} as const;\n\nexport type ProblemCode = (typeof PROBLEM_CODES)[number];\n\n/** Codes the mock platform answers before the platform contract lists them. */\nexport const PENDING_PROBLEM_CODES = ${literal(pendingCodes)} as const;\n`;
}

function rowsTs(calls, coverage) {
  return `${TS_HEADER}// The outbound-call table (contracts/generated/outbound-calls.json) and its row coverage.\n\nexport interface OutboundCallEndpoint {\n  readonly method: string;\n  readonly path: string;\n  readonly operation_id: string;\n  readonly status: 'pinned' | 'provisional' | 'pending_upstream';\n}\n\nexport interface OutboundCallRow {\n  readonly row: number;\n  readonly title: string;\n  readonly module: 'connect' | 'stats';\n  readonly group: string;\n  readonly integration: string | null;\n  readonly auth: string;\n  readonly endpoints: readonly OutboundCallEndpoint[];\n  readonly trigger: string;\n  readonly payload: string;\n  readonly cadence: string;\n  readonly disable: string;\n  readonly products: readonly string[];\n  readonly phase: number;\n}\n\nexport const ROWS: readonly OutboundCallRow[] = ${literal(calls.rows)};\n\nexport interface RowCoverage {\n  readonly row: number;\n  readonly operations: readonly { readonly operation_id: string; readonly method: string; readonly path: string; readonly success: readonly number[] }[];\n  readonly errors: readonly { readonly status: number; readonly code: string; readonly documented: boolean }[];\n}\n\nexport const ROW_COVERAGE: readonly RowCoverage[] = ${literal(coverage.rows)};\n`;
}

function rustConstants(ctx, dataFiles) {
  const strList = (items) => items.map((s) => `    ${JSON.stringify(s)},`).join('\n');
  const pairs = (entries) => entries.map(([k, p]) => `    (${JSON.stringify(k)}, include_str!(${JSON.stringify(p)})),`).join('\n');
  return `${RS_HEADER}//! The contract files, verbatim, and the constants products branch on.

/// \`contracts/constants.json\`.
pub const CONSTANTS_JSON: &str = include_str!("data/constants.json");

/// \`contracts/generated/outbound-calls.json\`: the outbound-call table.
pub const OUTBOUND_CALLS_JSON: &str = include_str!("data/outbound-calls.json");

/// \`contracts/generated/row-coverage.json\`.
pub const ROW_COVERAGE_JSON: &str = include_str!("data/row-coverage.json");

/// The JSON Schemas, by file name.
pub const SCHEMAS_JSON: &[(&str, &str)] = &[
${pairs(SCHEMA_DOCS.map((d) => [d.file, `data/schemas/${d.file}`]))}
];

/// The event schemas (envelope, common definitions, one per instance-audience type), by file name.
pub const EVENT_SCHEMAS_JSON: &[(&str, &str)] = &[
${pairs(dataFiles.filter((f) => f.startsWith('schemas/events/')).map((f) => [f.split('/').pop(), `data/${f}`]))}
];

/// The integration definitions, by key.
pub const INTEGRATIONS_JSON: &[(&str, &str)] = &[
${pairs(ctx.constants.integration_keys.map((k) => [k, `data/integrations/${k}.json`]))}
];

/// Every product code (\`demand\` accepts no connection).
pub const PRODUCTS: &[&str] = &[
${strList(ctx.constants.products)}
];

/// Every integration key a product can show.
pub const INTEGRATION_KEYS: &[&str] = &[
${strList(ctx.constants.integration_keys)}
];

/// The instance-audience event types.
pub const FEED_EVENT_TYPES: &[&str] = &[
${strList(ctx.constants.feed_event_types)}
];

/// The statistics signature headers.
pub const STATS_HEADER_KEY: &str = ${JSON.stringify(ctx.constants.stats_headers.key)};
/// The statistics signature header (\`ed25519=\` + signature).
pub const STATS_HEADER_SIGNATURE: &str = ${JSON.stringify(ctx.constants.stats_headers.signature)};
/// The optional statistics key id header.
pub const STATS_HEADER_KEY_ID: &str = ${JSON.stringify(ctx.constants.stats_headers.key_id)};

/// Every problem code of the contract, plus the codes pending upstream.
pub const PROBLEM_CODES: &[&str] = &[
${strList([...ctx.spec.components.schemas.ErrorCode.enum, ...ctx.pending.problem_codes.map((c) => c.code).filter((c) => !ctx.spec.components.schemas.ErrorCode.enum.includes(c))])}
];
`;
}

// ---------------------------------------------------------------------------------------- step 6
function renderTable(calls) {
  const esc = (s) => String(s).replace(/\|/g, '\\|');
  const productNames = { gauzy: 'Gauzy', teams: 'Teams', works: 'Works', rec: 'Rec', traduora: 'Traduora' };
  const lines = ['| # | Endpoint | Trigger | Payload | Cadence | How to disable | Products |', '|---|---|---|---|---|---|---|'];
  for (const r of calls.rows) {
    const endpoints = r.endpoints
      .map((e) => `\`${e.method} ${e.path}\`${e.status === 'pending_upstream' ? ' (pending upstream)' : ''}`)
      .join('<br>');
    const products = r.products.length === 5 ? 'all' : r.products.map((p) => productNames[p] ?? p).join(', ');
    const integration = r.integration ? ` Integration \`${r.integration}\`.` : '';
    lines.push(
      `| ${r.row} | ${endpoints} | ${esc(r.trigger)}.${integration} | ${esc(r.payload)} | ${esc(r.cadence)} | ${esc(r.disable)} | ${products} |`,
    );
  }
  return lines.join('\n');
}

function renderGroups(ctx) {
  const lines = ['| Group | Rows | Disable by |', '|---|---|---|'];
  const disable = {
    session: '*Disconnect* (or leave `EVER_CONNECT_ENABLED` unset)',
    connection: 'not connecting; *Disconnect*',
    integration: 'per integration in the product or in app.ever.co; for the whole installation with `EVER_CONNECT_INTEGRATIONS_DENY`',
    receipt: '*Disconnect*',
    sign_in: '*Disconnect*',
    stats: '`EVER_STATS_ENABLED=false` or the settings toggle',
  };
  for (const [group, label] of Object.entries(ctx.rowsDoc.groups)) {
    const rows = ctx.rowsDoc.rows
      .filter((r) => r.group === group)
      .map((r) => (r.integration ? `${r.row} \`${r.integration}\`` : String(r.row)));
    lines.push(`| ${label} | ${rows.join(', ')} | ${disable[group]} |`);
  }
  return lines.join('\n');
}

function renderIntro(ctx) {
  const connect = ctx.rowsDoc.rows.filter((r) => r.module === 'connect').map((r) => r.row);
  const stats = ctx.rowsDoc.rows.filter((r) => r.module === 'stats').map((r) => r.row);
  const consented = ctx.rowsDoc.rows.filter((r) => r.integration).map((r) => r.row);
  const ranges = (nums) => {
    const out = [];
    let start = nums[0];
    let prev = nums[0];
    for (const n of [...nums.slice(1), Number.NaN]) {
      if (n === prev + 1) {
        prev = n;
        continue;
      }
      out.push(start === prev ? `${start}` : `${start}–${prev}`);
      start = n;
      prev = n;
    }
    return out.join(', ');
  };
  // The connect calls themselves are the rows a "do not connect" disables; every other connection
  // row needs a connection.
  const connecting = ctx.rowsDoc.rows.filter((r) => r.module === 'connect' && r.disable === 'do not connect').map((r) => r.row);
  return `Rows ${ranges(connect)} belong to the connection module and row ${ranges(stats)} to the statistics module. Each row runs only on the trigger it names: the connect calls (rows ${connecting.join(', ')}) when an operator starts a connection, every other connection-module row only while connected. Rows ${ranges(consented)} also need an active consent for the named integration, recorded by Ever Platform. The table holds ${ctx.rowsDoc.rows.length} rows; a row marked *pending upstream* is answered by the mock platform and documented here before the Ever Platform API publishes it.`;
}

/** Every problem code an outbound call can receive, from the rows' documented error pairs. */
function renderProblemCodes(ctx) {
  const codes = [...new Set(ctx.rowsDoc.rows.flatMap((r) => (r.errors ?? []).map((e) => e[1])))].sort();
  return codes.map((c) => `\`${c}\``).join(', ');
}

function fillRegion(text, name, body, file) {
  const start = `<!-- generated:${name} -->`;
  const end = `<!-- /generated:${name} -->`;
  const i = text.indexOf(start);
  const j = text.indexOf(end);
  if (i < 0 || j < i) throw new Error(`${file}: the ${start} … ${end} markers are missing`);
  return `${text.slice(0, i + start.length)}\n${body}\n${text.slice(j)}`;
}

function docs(ctx, calls) {
  const out = {};
  const outbound = 'docs/outbound-calls.md';
  if (existsSync(join(REPO, outbound))) {
    let text = lf(readText(outbound));
    text = fillRegion(text, 'outbound-intro', renderIntro(ctx), outbound);
    text = fillRegion(text, 'outbound-calls', renderTable(calls), outbound);
    text = fillRegion(text, 'outbound-groups', renderGroups(ctx), outbound);
    text = fillRegion(text, 'outbound-problems', renderProblemCodes(ctx), outbound);
    out[outbound] = text;
  }
  const stats = 'docs/stats-schema.md';
  const golden = 'contracts/fixtures/stats/valid/gauzy.json';
  if (existsSync(join(REPO, stats)) && existsSync(join(REPO, golden))) {
    const example = `\`\`\`json\n${JSON.stringify(readJson(join(REPO, golden)), null, 2)}\n\`\`\``;
    out[stats] = fillRegion(lf(readText(stats)), 'stats-example', example, stats);
  }
  const integrationsDoc = 'docs/integrations.md';
  if (existsSync(join(REPO, integrationsDoc))) {
    const lines = ['| Key | What it does | Direction | Ever Cloud / self-hosted | Products | Status |', '|---|---|---|---|---|---|'];
    for (const key of ctx.constants.integration_keys) {
      const d = ctx.integrations[key];
      lines.push(
        `| \`${key}\` | ${d.name}: ${d.description.replace(/\|/g, '\\|')} | ${d.direction} | ${d.availability.cloud} / ${d.availability.self_hosted} | ${d.products.join(', ')} | ${d.status.replace('_', ' ')} |`,
      );
    }
    out[integrationsDoc] = fillRegion(lf(readText(integrationsDoc)), 'integrations-catalog', lines.join('\n'), integrationsDoc);
  }
  return out;
}

// ---------------------------------------------------------------------------------------------
export async function generateAll() {
  const ctx = load();
  lint(ctx);
  const calls = outboundCalls(ctx);
  const coverage = rowCoverage(ctx);
  const files = {};
  files[`${TS}/ever-platform.v1.ts`] = await openapiTypes(ctx);
  files[`${TS}/schemas.ts`] = await schemaTypes(ctx);
  Object.assign(files, rustTypes(ctx));
  files[`${TS}/integrations.ts`] = integrationsTs(ctx);
  files[`${TS}/constants.ts`] = constantsTs(ctx);
  files[`${TS}/rows.ts`] = rowsTs(calls, coverage);
  files[`${TS}/problems.ts`] = problemsTs(ctx);
  files['contracts/generated/ever-platform.v1.json'] = stableJson(ctx.spec, { sort: false });
  files['contracts/generated/outbound-calls.json'] = stableJson(calls, { sort: false });
  files['contracts/generated/row-coverage.json'] = stableJson(coverage, { sort: false });

  // The crate carries its own copy of the contract files, so it builds on its own.
  const dataFiles = [];
  const copy = (from, to) => {
    files[`${RS}/data/${to}`] = from.startsWith('contracts/generated/') ? files[from] : lf(readText(from));
    dataFiles.push(to);
  };
  copy('contracts/constants.json', 'constants.json');
  copy('contracts/generated/outbound-calls.json', 'outbound-calls.json');
  copy('contracts/generated/row-coverage.json', 'row-coverage.json');
  for (const d of SCHEMA_DOCS) copy(`contracts/schemas/${d.file}`, `schemas/${d.file}`);
  copy('contracts/schemas/events/envelope.schema.json', 'schemas/events/envelope.schema.json');
  copy('contracts/schemas/events/common.schema.json', 'schemas/events/common.schema.json');
  for (const { file } of Object.values(ctx.events)) copy(`contracts/schemas/events/${file}`, `schemas/events/${file}`);
  for (const key of ctx.constants.integration_keys) copy(`contracts/integrations/${key}.json`, `integrations/${key}.json`);
  files[`${RS}/constants.rs`] = rustConstants(ctx, dataFiles);

  // The mock platform carries the contract files it serves and validates against, so its
  // directory (and its image) builds on its own.
  const MOCK = 'tools/mock-platform/contracts';
  const mockCopy = (from) => {
    files[`${MOCK}/${from.replace(/^contracts\//, '')}`] = from.startsWith('contracts/generated/') ? files[from] : lf(readText(from));
  };
  for (const f of [
    'contracts/generated/ever-platform.v1.json',
    'contracts/generated/outbound-calls.json',
    'contracts/generated/row-coverage.json',
  ])
    mockCopy(f);
  for (const f of [
    'contracts/openapi/pending-upstream.json',
    'contracts/constants.json',
    'contracts/integrations/catalog.v1.json',
    'contracts/fixtures/lookup/test-vectors.json',
  ])
    mockCopy(f);
  for (const d of SCHEMA_DOCS) mockCopy(`contracts/schemas/${d.file}`);
  mockCopy('contracts/schemas/events/envelope.schema.json');
  mockCopy('contracts/schemas/events/common.schema.json');
  for (const { file } of Object.values(ctx.events)) mockCopy(`contracts/schemas/events/${file}`);
  for (const key of ctx.constants.integration_keys) mockCopy(`contracts/integrations/${key}.json`);
  // The egress self-test's statistics sender posts a golden report of the statistics schema.
  files['tools/egress-audit/selftest/stats-sender/report.json'] = lf(readText('contracts/fixtures/stats/valid/gauzy.json'));
  files['crates/ever-connect-contracts/tests/typed/mod.rs'] = rustTypedDispatch(ctx);

  // rustfmt (pinned by rust-toolchain.toml) gives the Rust output the repository's style.
  for (const path of Object.keys(files).filter((p) => p.endsWith('.rs'))) files[path] = rustfmt(files[path]);

  Object.assign(files, docs(ctx, calls));
  const lock = Object.fromEntries(
    Object.keys(files)
      .sort()
      .map((p) => [p, sha256(files[p])]),
  );
  files['generated.lock'] = stableJson({ description: 'sha256 of every file tools/generate.mjs writes', files: lock }, { sort: false });
  return files;
}

async function main() {
  const check = process.argv.includes('--check');
  const files = await generateAll();
  const current = {};
  for (const path of Object.keys(files))
    current[path] = existsSync(join(REPO, path)) ? lf(readFileSync(join(REPO, path), 'utf8')) : undefined;
  // Generated files that are no longer produced (a removed integration or event type).
  for (const dir of [`${RS}/data/integrations`, `${RS}/data/schemas/events`]) {
    if (!existsSync(join(REPO, dir))) continue;
    for (const name of readdirSync(join(REPO, dir))) {
      const path = `${dir}/${name}`;
      if (!(path in files)) current[path] = readFileSync(join(REPO, path), 'utf8');
    }
  }
  const differing = diffOutputs(files, current);
  if (check) {
    if (differing.length > 0) {
      process.stderr.write(
        `generate --check: ${differing.length} generated file(s) differ from the contract:\n  ${differing.join('\n  ')}\nRun: pnpm generate\n`,
      );
      process.exit(1);
    }
    try {
      execFileSync('git', ['diff', '--exit-code', '--stat', '--', ...Object.keys(files)], { cwd: REPO, stdio: ['ignore', 'pipe', 'pipe'] });
    } catch (error) {
      process.stderr.write(`generate --check: generated files have uncommitted changes:\n${error.stdout?.toString() ?? ''}`);
      process.exit(1);
    }
    process.stdout.write(`generate --check: ok (${Object.keys(files).length} files)\n`);
    return;
  }
  for (const path of differing) {
    if (files[path] === undefined) rmSync(join(REPO, path));
    else writeText(join(REPO, path), files[path]);
  }
  process.stdout.write(`generate: ${differing.length} file(s) written (${Object.keys(files).length} generated files)\n`);
}

if (process.argv[1]?.endsWith('generate.mjs')) {
  main().catch((error) => {
    process.stderr.write(`generate: ${error.message}\n`);
    process.exit(1);
  });
}
